# Checkov configuration for Azure Terraform modules
# This file configures Checkov security scanning

framework: terraform

# Compact output
compact: true

# Directory to scan
directory: ./

# Exclude directories
skip-path:
  - .git/
  - .terraform/
  - test/
  - examples/
  - docs/

# Skip specific checks
skip-check:
  - CKV_AZURE_119  # NICs with public IPs allowed by design

# Filter checks by policy metadata (optional)
policy-metadata-filter: "category=security,provider=azure,framework=terraform"

quiet: false

# Soft fail mode (exit code 0 even on failures)
soft-fail: false
