name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TF_VERSION: "1.9.0"
  GO_VERSION: "1.22"

jobs:
  docs-tests:
    name: Documentation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Install documentation tools
        run: |
          go install github.com/terraform-docs/terraform-docs@latest

      - name: Validate documentation
        run: |
          # Check if all modules have README files
          missing_readmes=()
          for module in azure-* modules/azure-*; do
            if [[ -d "$module" ]] && [[ ! -f "$module/README.md" ]]; then
              missing_readmes+=("$module")
            fi
          done

          if [[ ${#missing_readmes[@]} -gt 0 ]]; then
            echo "::error::Missing README.md in the following modules:"
            printf '  - %s\n' "${missing_readmes[@]}"
            exit 1
          fi
