name: Test Azure Terraform Modules Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TF_VERSION: "1.6.0"
  GO_VERSION: "1.21"

jobs:
  docs-tests:
    name: Documentation Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install documentation tools
        run: |
          go install github.com/terraform-docs/terraform-docs@latest

      - name: Validate documentation
        run: |
          # Check if all modules have README files
          for module in azure-*/; do
            if [ ! -f "$module/README.md" ]; then
              echo "Missing README.md for module: $module"
              exit 1
            fi
          done

      - name: Generate documentation
        run: |
          # Generate documentation for each module
          for module in azure-*/; do
            echo "Generating docs for $module"
            cd "$module"
            terraform-docs markdown table --output-file README.md --output-mode inject . || true
            cd ..
          done

